version: "3.7"
services:
    app:
        container_name: talentpool_test_app
        restart: always
        build: .
        environment:
            MONGO_URI: "mongodb://mongo:27017/test"
            DATABASE_USER: ""
            DATABASE_PASSWORD: ""

        volumes:
            - ./data:/data/db
        ports:
            - "8888:3333"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"